-- =====================================================
-- TrenerMaturalny: Live Database Patch
-- Generated: 2026-03-23
--
-- Apply this to an EXISTING database to fix:
--   1. Wrong/NULL algo_task solutions (all 37 tasks)
--   2. Duplicate test cases in algo_task_tests
--   3. Duplicate quiz questions
--
-- Usage: mysql -u root -p matura_db < patch_live_db.sql
-- =====================================================

-- ===== PART 1: Fix algo_task solutions =====

UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nbool pierwsza(long long n){\n    if(n < 2) return false;\n    if(n == 2) return true;\n    if(n % 2 == 0) return false;\n    for(long long i = 3; i * i <= n; i += 2)\n        if(n % i == 0) return false;\n    return true;\n}\nint main(){\n    long long n; cin >> n;\n    cout << (pierwsza(n) ? "TAK" : "NIE") << endl;\n    return 0;\n}' WHERE id = 1;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    bool first = true;\n    for(int i = 2; (long long)i*i <= n; i++){\n        int cnt = 0;\n        while(n % i == 0){ cnt++; n /= i; }\n        if(cnt > 0){\n            if(!first) cout << " * ";\n            cout << i;\n            if(cnt > 1) cout << "^" << cnt;\n            first = false;\n        }\n    }\n    if(n > 1){\n        if(!first) cout << " * ";\n        cout << n;\n    }\n    cout << endl;\n    return 0;\n}' WHERE id = 2;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int& x : a) cin >> x;\n    int k; cin >> k;\n    int lo = 0, hi = n-1, pos = -1;\n    while(lo <= hi){\n        int mid = (lo+hi)/2;\n        if(a[mid] == k){ pos = mid; break; }\n        else if(a[mid] < k) lo = mid+1;\n        else hi = mid-1;\n    }\n    cout << pos << endl;\n    return 0;\n}' WHERE id = 3;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long n; cin >> n;\n    if(n == 0){ cout << 0; return 0; }\n    string bin = "";\n    while(n > 0){ bin = char(\\'0\\' + n%2) + bin; n /= 2; }\n    cout << bin << endl;\n    return 0;\n}' WHERE id = 4;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long a, b;\n    cin >> a >> b;\n    while(b != 0){\n        long long r = a % b;\n        a = b; b = r;\n    }\n    cout << a << endl;\n    return 0;\n}' WHERE id = 5;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int i = 0; i < n; i++) cin >> a[i];\n    int shifts = 0;\n    for(int i = 1; i < n; i++){\n        int key = a[i], j = i-1;\n        while(j >= 0 && a[j] > key){\n            a[j+1] = a[j];\n            j--;\n            shifts++;\n        }\n        a[j+1] = key;\n    }\n    for(int i = 0; i < n; i++){\n        if(i) cout << " ";\n        cout << a[i];\n    }\n    cout << "\\\\n" << shifts << endl;\n    return 0;\n}' WHERE id = 6;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<bool> sito(n+1, true);\n    sito[0] = sito[1] = false;\n    for(int i = 2; i * i <= n; i++)\n        if(sito[i])\n            for(int j = i*i; j <= n; j += i)\n                sito[j] = false;\n    for(int i = 2; i <= n; i++)\n        if(sito[i]) cout << i << "\n";\n    return 0;\n}' WHERE id = 7;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long n; cin >> n;\n    if(n <= 1){ cout << "NIE" << endl; return 0; }\n    long long sum = 1;\n    for(long long i = 2; i * i <= n; i++){\n        if(n % i == 0){\n            sum += i;\n            if(i != n/i) sum += n/i;\n        }\n    }\n    cout << (sum == n ? "TAK" : "NIE") << endl;\n    return 0;\n}' WHERE id = 8;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long n;\n    cin >> n;\n    if(n == 0){ cout << 0; return 0; }\n    string res = "";\n    while(n > 0){\n        int r = n % 16;\n        res = char(r < 10 ? \\'0\\'+r : \\'A\\'+(r-10)) + res;\n        n /= 16;\n    }\n    cout << res << endl;\n    return 0;\n}' WHERE id = 9;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long n; int b; cin >> n >> b;\n    if(n == 0){ cout << 0; return 0; }\n    string res = "";\n    while(n > 0){\n        int r = n % b;\n        res = char(r < 10 ? \\'0\\'+r : \\'A\\'+(r-10)) + res;\n        n /= b;\n    }\n    cout << res << endl;\n    return 0;\n}' WHERE id = 10;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long a, b;\n    cin >> a >> b;\n    long long p = a, q = b;\n    while(q != 0){ long long r = p % q; p = q; q = r; }\n    cout << p << "\\\\n" << (a / p) * b << endl;\n    return 0;\n}' WHERE id = 11;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    string a, b; cin >> a >> b;\n    sort(a.begin(), a.end());\n    sort(b.begin(), b.end());\n    cout << (a == b ? "TAK" : "NIE") << endl;\n    return 0;\n}' WHERE id = 12;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    string t, w;\n    getline(cin, t);\n    getline(cin, w);\n    int n = t.size(), m = w.size();\n    bool found = false;\n    for(int i = 0; i <= n - m; i++){\n        bool match = true;\n        for(int j = 0; j < m; j++){\n            if(t[i+j] != w[j]){ match = false; break; }\n        }\n        if(match){\n            cout << i << "\\\\n";\n            found = true;\n        }\n    }\n    if(!found) cout << "BRAK" << endl;\n    return 0;\n}' WHERE id = 13;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    string s;\n    getline(cin, s);\n    int k; cin >> k;\n    k = ((k % 26) + 26) % 26;\n    for(char& c : s){\n        if(c>=\\'a\\'&&c<=\\'z\\') c = \\'a\\' + (c-\\'a\\'+k)%26;\n        else if(c>=\\'A\\'&&c<=\\'Z\\') c = \\'A\\' + (c-\\'A\\'+k)%26;\n    }\n    cout << s << endl;\n    return 0;\n}' WHERE id = 14;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint cnt = 0;\nlong long nwd(long long a, long long b){\n    cnt++;\n    if(b == 0) return a;\n    return nwd(b, a % b);\n}\nint main(){\n    long long a, b;\n    cin >> a >> b;\n    long long g = nwd(a, b);\n    cout << g << "\\\\n" << cnt << endl;\n    return 0;\n}' WHERE id = 16;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int i = 0; i < n; i++) cin >> a[i];\n    int mn = a[0], mx = a[0];\n    int cmp = 0;\n    int i = 1;\n    for(; i + 1 < n; i += 2){\n        int lo, hi;\n        cmp++;\n        if(a[i] < a[i+1]){ lo = a[i]; hi = a[i+1]; }\n        else { lo = a[i+1]; hi = a[i]; }\n        cmp++;\n        if(lo < mn) mn = lo;\n        cmp++;\n        if(hi > mx) mx = hi;\n    }\n    if(i < n){\n        cmp++;\n        if(a[i] < mn) mn = a[i];\n        else { cmp++; if(a[i] > mx) mx = a[i]; }\n    }\n    cout << mn << "\\\\n" << mx << "\\\\n" << cmp << endl;\n    return 0;\n}' WHERE id = 17;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint cmpCnt = 0;\nvoid mergeSort(vector<int>& a, int l, int r){\n    if(l >= r) return;\n    int mid = (l + r) / 2;\n    mergeSort(a, l, mid);\n    mergeSort(a, mid + 1, r);\n    vector<int> tmp;\n    int i = l, j = mid + 1;\n    while(i <= mid && j <= r){\n        cmpCnt++;\n        if(a[i] <= a[j]) tmp.push_back(a[i++]);\n        else tmp.push_back(a[j++]);\n    }\n    while(i <= mid) tmp.push_back(a[i++]);\n    while(j <= r) tmp.push_back(a[j++]);\n    for(int k = l; k <= r; k++) a[k] = tmp[k - l];\n}\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int i = 0; i < n; i++) cin >> a[i];\n    mergeSort(a, 0, n - 1);\n    for(int i = 0; i < n; i++){\n        if(i) cout << " ";\n        cout << a[i];\n    }\n    cout << "\\\\n" << cmpCnt << endl;\n    return 0;\n}' WHERE id = 18;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\ndouble f(double x){ return x*x*x - x - 2; }\nint main(){\n    double a, b, eps;\n    cin >> a >> b >> eps;\n    for(int i = 0; i < 200 && b - a > eps * 0.01; i++){\n        double mid = (a + b) / 2.0;\n        if(f(a) * f(mid) <= 0) b = mid;\n        else a = mid;\n    }\n    printf("%.6f\\\\n", (a + b) / 2.0);\n    return 0;\n}' WHERE id = 19;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    double X;\n    cin >> X;\n    double eps = 1e-9;\n    double x = X;\n    if(x == 0){ printf("%.6f\\\\n", 0.0); return 0; }\n    while(true){\n        double nx = (x + X / x) / 2.0;\n        if(fabs(nx - x) < eps) break;\n        x = nx;\n    }\n    printf("%.6f\\\\n", x);\n    return 0;\n}' WHERE id = 20;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<long long> a(n + 1);\n    for(int i = 0; i <= n; i++) cin >> a[i];\n    long long x; cin >> x;\n    long long w = a[0];\n    for(int i = 1; i <= n; i++) w = w * x + a[i];\n    cout << w << endl;\n    return 0;\n}' WHERE id = 21;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long b, e;\n    cin >> b >> e;\n    long long mod = 1000000007;\n    long long result = 1;\n    b %= mod;\n    while(e > 0){\n        if(e & 1) result = result * b % mod;\n        b = b * b % mod;\n        e >>= 1;\n    }\n    cout << result << endl;\n    return 0;\n}' WHERE id = 22;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nconst long long MOD = 1000000007;\nint depth = 0;\nlong long fpow(long long b, long long e){\n    depth++;\n    if(e == 0) return 1;\n    long long t = fpow(b, e / 2);\n    t = t * t % MOD;\n    if(e % 2 == 1) t = t * b % MOD;\n    return t;\n}\nint main(){\n    long long b, e;\n    cin >> b >> e;\n    b %= MOD;\n    long long res = fpow(b, e);\n    cout << res << "\\\\n" << depth << endl;\n    return 0;\n}' WHERE id = 23;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    long long L, n;\n    cin >> L >> n;\n    long long num = L;\n    long long den = 1;\n    for(int i = 0; i < n; i++){\n        num *= 4;\n        den *= 3;\n    }\n    long long a = num, b = den;\n    while(b != 0){ long long r = a % b; a = b; b = r; }\n    cout << num / a << "/" << den / a << endl;\n    return 0;\n}' WHERE id = 24;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    string a, b; cin >> a >> b;\n    int n = a.size(), m = b.size();\n    vector<vector<int>> dp(n+1, vector<int>(m+1, 0));\n    for(int i = 1; i <= n; i++)\n        for(int j = 1; j <= m; j++)\n            if(a[i-1] == b[j-1]) dp[i][j] = dp[i-1][j-1] + 1;\n            else dp[i][j] = max(dp[i-1][j], dp[i][j-1]);\n    cout << dp[n][m] << "\\\\n";\n    string lcs = "";\n    int i = n, j = m;\n    while(i > 0 && j > 0){\n        if(a[i-1] == b[j-1]){ lcs = a[i-1] + lcs; i--; j--; }\n        else if(dp[i-1][j] >= dp[i][j-1]) i--;\n        else j--;\n    }\n    cout << lcs << endl;\n    return 0;\n}' WHERE id = 26;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint prec(char c){ return (c==\\'*\\'||c==\\'/\\')?2:1; }\nint main(){\n    string line;\n    getline(cin, line);\n    istringstream iss(line);\n    vector<string> onp;\n    stack<char> ops;\n    string tok;\n    while(iss >> tok){\n        if(tok == "(") ops.push(\\'(\\');\n        else if(tok == ")"){\n            while(ops.top() != \\'(\\'){\n                string s(1, ops.top()); onp.push_back(s); ops.pop();\n            }\n            ops.pop();\n        } else if(tok=="+"||tok=="-"||tok=="*"||tok=="/"){\n            char c = tok[0];\n            while(!ops.empty() && ops.top()!=\\'(\\' && prec(ops.top())>=prec(c)){\n                string s(1, ops.top()); onp.push_back(s); ops.pop();\n            }\n            ops.push(c);\n        } else {\n            onp.push_back(tok);\n        }\n    }\n    while(!ops.empty()){\n        string s(1, ops.top()); onp.push_back(s); ops.pop();\n    }\n    for(int i = 0; i < (int)onp.size(); i++){\n        if(i) cout << " ";\n        cout << onp[i];\n    }\n    cout << "\\\\n";\n    stack<long long> st;\n    for(auto& t : onp){\n        if(t=="+"||t=="-"||t=="*"||t=="/"){\n            long long b = st.top(); st.pop();\n            long long a = st.top(); st.pop();\n            if(t=="+") st.push(a+b);\n            else if(t=="-") st.push(a-b);\n            else if(t=="*") st.push(a*b);\n            else st.push(a/b);\n        } else {\n            st.push(stoll(t));\n        }\n    }\n    cout << st.top() << endl;\n    return 0;\n}' WHERE id = 27;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int q, k;\n    cin >> q >> k;\n    vector<int> nom(k);\n    for(int i = 0; i < k; i++) cin >> nom[i];\n    if(q == 0){ cout << 0 << endl; return 0; }\n    int total = 0;\n    vector<pair<int,int>> used;\n    for(int i = 0; i < k; i++){\n        int cnt = q / nom[i];\n        if(cnt > 0){\n            total += cnt;\n            q -= cnt * nom[i];\n        }\n        used.push_back({nom[i], cnt});\n    }\n    cout << total << "\\\\n";\n    for(auto& p : used){\n        cout << p.first << " x " << p.second << "\\\\n";\n    }\n    return 0;\n}' WHERE id = 28;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int& x : a) cin >> x;\n    vector<int> dp(n, 1), prev(n, -1);\n    for(int i = 1; i < n; i++)\n        for(int j = 0; j < i; j++)\n            if(a[j] < a[i] && dp[j] + 1 >= dp[i]){\n                dp[i] = dp[j] + 1;\n                prev[i] = j;\n            }\n    int mx = *max_element(dp.begin(), dp.end());\n    int idx = -1;\n    for(int i = n - 1; i >= 0; i--)\n        if(dp[i] == mx){ idx = i; break; }\n    cout << mx << "\\\\n";\n    vector<int> seq;\n    for(int i = idx; i != -1; i = prev[i]) seq.push_back(a[i]);\n    reverse(seq.begin(), seq.end());\n    for(int i = 0; i < (int)seq.size(); i++){\n        if(i) cout << " ";\n        cout << seq[i];\n    }\n    cout << endl;\n    return 0;\n}' WHERE id = 29;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    cin.ignore();\n    vector<int> st;\n    for(int i = 0; i < n; i++){\n        string line;\n        getline(cin, line);\n        if(line.substr(0, 4) == "PUSH"){\n            int x = stoi(line.substr(5));\n            st.push_back(x);\n        } else if(line == "POP"){\n            cout << st.back() << "\\\\n";\n            st.pop_back();\n        } else if(line == "TOP"){\n            cout << st.back() << "\\\\n";\n        } else if(line == "EMPTY"){\n            cout << (st.empty() ? 1 : 0) << "\\\\n";\n        }\n    }\n    return 0;\n}' WHERE id = 31;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    cin.ignore();\n    queue<int> q;\n    for(int i = 0; i < n; i++){\n        string line;\n        getline(cin, line);\n        if(line.substr(0, 7) == "ENQUEUE"){\n            int x = stoi(line.substr(8));\n            q.push(x);\n        } else if(line == "DEQUEUE"){\n            cout << q.front() << "\\\\n";\n            q.pop();\n        } else if(line == "FRONT"){\n            cout << q.front() << "\\\\n";\n        } else if(line == "EMPTY"){\n            cout << (q.empty() ? 1 : 0) << "\\\\n";\n        }\n    }\n    return 0;\n}' WHERE id = 32;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint depth_cnt = 0;\nint bsearch(vector<int>& a, int l, int r, int x){\n    depth_cnt++;\n    if(l > r) return -1;\n    int mid = (l + r) / 2;\n    if(a[mid] == x) return mid;\n    if(x < a[mid]) return bsearch(a, l, mid - 1, x);\n    return bsearch(a, mid + 1, r, x);\n}\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int i = 0; i < n; i++) cin >> a[i];\n    int x; cin >> x;\n    int pos = bsearch(a, 0, n - 1, x);\n    cout << pos << "\\\\n" << depth_cnt << endl;\n    return 0;\n}' WHERE id = 33;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nlong long memo[51];\nbool computed[51];\nlong long fib(int n){\n    if(computed[n]) return memo[n];\n    computed[n] = true;\n    if(n <= 1){ memo[n] = n; return n; }\n    memo[n] = fib(n-1) + fib(n-2);\n    return memo[n];\n}\nint main(){\n    int n; cin >> n;\n    memset(computed, false, sizeof(computed));\n    long long res = fib(n);\n    cout << res << "\\\\n" << n + 1 << endl;\n    return 0;\n}' WHERE id = 34;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n, m; cin >> n >> m;\n    vector<vector<int>> adj(n+1);\n    for(int i = 0; i < m; i++){\n        int u, v; cin >> u >> v;\n        adj[u].push_back(v); adj[v].push_back(u);\n    }\n    int s, t; cin >> s >> t;\n    vector<int> dist(n+1, -1);\n    queue<int> q;\n    dist[s] = 0; q.push(s);\n    while(!q.empty()){\n        int u = q.front(); q.pop();\n        for(int v : adj[u]) if(dist[v]==-1){ dist[v]=dist[u]+1; q.push(v); }\n    }\n    cout << dist[t] << endl;\n    return 0;\n}' WHERE id = 35;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int i = 0; i < n; i++) cin >> a[i];\n    int swaps = 0;\n    for(int i = 0; i < n-1; i++)\n        for(int j = 0; j < n-1-i; j++)\n            if(a[j] > a[j+1]){ swap(a[j], a[j+1]); swaps++; }\n    for(int i = 0; i < n; i++){\n        if(i) cout << " ";\n        cout << a[i];\n    }\n    cout << "\\\\n" << swaps << endl;\n    return 0;\n}' WHERE id = 36;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint cmpCnt = 0;\nint partition(vector<int>& a, int l, int r){\n    int pivot = a[r], i = l - 1;\n    for(int j = l; j < r; j++){\n        cmpCnt++;\n        if(a[j] <= pivot){ i++; swap(a[i], a[j]); }\n    }\n    swap(a[i+1], a[r]);\n    return i + 1;\n}\nvoid qsort(vector<int>& a, int l, int r){\n    if(l >= r) return;\n    int p = partition(a, l, r);\n    int lo = p, hi = p;\n    while(lo > l && a[lo-1] == a[p]) lo--;\n    while(hi < r && a[hi+1] == a[p]) hi++;\n    qsort(a, l, lo - 1);\n    qsort(a, hi + 1, r);\n}\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int i = 0; i < n; i++) cin >> a[i];\n    qsort(a, 0, n - 1);\n    for(int i = 0; i < n; i++){\n        if(i) cout << " ";\n        cout << a[i];\n    }\n    cout << "\\\\n" << cmpCnt << endl;\n    return 0;\n}' WHERE id = 37;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n; cin >> n;\n    vector<int> a(n);\n    for(int i = 0; i < n; i++) cin >> a[i];\n    int x; cin >> x;\n    int pos = -1, cmp = 0;\n    for(int i = 0; i < n; i++){\n        cmp++;\n        if(a[i] == x){ pos = i; break; }\n    }\n    cout << pos << "\\\\n" << cmp << endl;\n    return 0;\n}' WHERE id = 38;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    int n;\n    cin >> n;\n    if(n == 0){ cout << 0; return 0; }\n    long long a = 0, b = 1;\n    for(int i = 2; i <= n; i++){\n        long long c = a + b;\n        a = b; b = c;\n    }\n    cout << b << endl;\n    return 0;\n}' WHERE id = 39;
UPDATE matura_db.algo_tasks SET solution = '#include <bits/stdc++.h>\nusing namespace std;\nint main(){\n    string s; cin >> s;\n    string r = s; reverse(r.begin(), r.end());\n    cout << (s == r ? "TAK" : "NIE") << endl;\n    return 0;\n}' WHERE id = 40;

-- ===== PART 2: Remove duplicate test cases =====
-- Keep only the row with the lowest ID for each unique (task_id, test_name, input_data, expected)

DROP TABLE IF EXISTS matura_db._dedup_keep;

CREATE TABLE matura_db._dedup_keep AS
SELECT MIN(id) AS id FROM matura_db.algo_task_tests
GROUP BY task_id, test_name, input_data, expected;

DELETE FROM matura_db.algo_task_tests
WHERE id NOT IN (SELECT id FROM matura_db._dedup_keep);

DROP TABLE matura_db._dedup_keep;

-- ===== PART 3: Remove duplicate quiz questions =====
-- Keep only the row with the lowest ID for each unique (category, question)

DROP TABLE IF EXISTS matura_db._dedup_quiz_keep;

CREATE TABLE matura_db._dedup_quiz_keep AS
SELECT MIN(id) AS id FROM matura_db.quiz_questions
GROUP BY category, question;

DELETE FROM matura_db.quiz_questions
WHERE id NOT IN (SELECT id FROM matura_db._dedup_quiz_keep);

DROP TABLE matura_db._dedup_quiz_keep;

-- ===== Verification =====
SELECT 'algo_tasks' AS tbl, COUNT(*) AS cnt FROM matura_db.algo_tasks
UNION ALL
SELECT 'algo_task_tests', COUNT(*) FROM matura_db.algo_task_tests
UNION ALL
SELECT 'quiz_questions', COUNT(*) FROM matura_db.quiz_questions;
