INSERT INTO matura_db.sql_tasks (scenario_id,title,difficulty,description,hint,solution,is_active,created_at) VALUES
	 (1,'Zadanie 1. (0–2) Najbardziej aktywny czytelnik','hard','Podaj imię i nazwisko czytelnika, który wypożyczył łącznie najwięcej książek (uwzględnij wszystkie wypożyczenia, również te gdzie książka nie została jeszcze zwrócona). Jeśli jest kilku takich czytelników, wypisz wszystkich — posortuj alfabetycznie po nazwisku.','Użyj GROUP BY c.id z COUNT(*), następnie ogranicz wynik do MAX za pomocą podzapytania lub HAVING COUNT(*)=(SELECT MAX(cnt) FROM ...).','SELECT c.imie, c.nazwisko FROM czytelnicy c JOIN wypozyczenia w ON c.id=w.czytelnik_id GROUP BY c.id HAVING COUNT(*)=(SELECT MAX(cnt) FROM (SELECT COUNT(*) as cnt FROM wypozyczenia GROUP BY czytelnik_id) sub) ORDER BY c.nazwisko',1,'2026-03-14 20:19:28'),
	 (1,'Zadanie 2. (0–2) Książki nigdy nie wypożyczone','hard','Podaj tytuły książek, które nie zostały ani razu wypożyczone. Posortuj alfabetycznie po tytule.','Użyj NOT IN z podzapytaniem: WHERE id NOT IN (SELECT DISTINCT ksiazka_id FROM wypozyczenia).','SELECT tytul FROM ksiazki WHERE id NOT IN (SELECT DISTINCT ksiazka_id FROM wypozyczenia) ORDER BY tytul',1,'2026-03-14 20:19:28'),
	 (1,'Zadanie 3. (0–2) Gatunek z największą łączną liczbą stron','hard','Podaj nazwę gatunku, dla którego suma liczby stron wszystkich książek tego gatunku jest największa. Istnieje dokładnie jeden taki gatunek.','GROUP BY gatunek, ORDER BY SUM(liczba_stron) DESC LIMIT 1.','SELECT gatunek FROM ksiazki GROUP BY gatunek ORDER BY SUM(liczba_stron) DESC LIMIT 1',1,'2026-03-14 20:19:28'),
	 (1,'Zadanie 4. (0–2) Czytelnicy przetrzymujący więcej niż 2 książki','hard','Podaj imię i nazwisko czytelników, którzy aktualnie przetrzymują więcej niż 2 nieoddane książki (data_zwrotu IS NULL). Posortuj po nazwisku.','WHERE w.data_zwrotu IS NULL GROUP BY c.id HAVING COUNT(*) > 2.','SELECT c.imie, c.nazwisko FROM czytelnicy c JOIN wypozyczenia w ON c.id=w.czytelnik_id WHERE w.data_zwrotu IS NULL GROUP BY c.id HAVING COUNT(*)>2 ORDER BY c.nazwisko',1,'2026-03-14 20:19:28'),
	 (1,'Zadanie 5. (0–2) Najdłużej przetrzymana książka','hard','Podaj tytuł książki, która była wypożyczona najdłużej (największa liczba dni między data_wypozyczenia a data_zwrotu). Uwzględniaj tylko zakończone wypożyczenia. Istnieje dokładnie jeden taki rekord.','Użyj julianday(data_zwrotu) - julianday(data_wypozyczenia) do obliczenia liczby dni. ORDER BY ... DESC LIMIT 1.','SELECT k.tytul FROM ksiazki k JOIN wypozyczenia w ON k.id=w.ksiazka_id WHERE w.data_zwrotu IS NOT NULL ORDER BY (julianday(w.data_zwrotu)-julianday(w.data_wypozyczenia)) DESC LIMIT 1',1,'2026-03-14 20:19:28'),
	 (1,'Zadanie 6. (0–2) Średni czas wypożyczenia wg gatunku','hard','Dla każdego gatunku oblicz średni czas wypożyczenia w dniach (zaokrąglony do 1 miejsca po przecinku), uwzględniając tylko zakończone wypożyczenia. Posortuj malejąco po średnim czasie.','AVG(julianday(data_zwrotu) - julianday(data_wypozyczenia)), GROUP BY gatunek, ORDER BY srednia DESC.','SELECT k.gatunek, ROUND(AVG(julianday(w.data_zwrotu)-julianday(w.data_wypozyczenia)),1) as srednia FROM ksiazki k JOIN wypozyczenia w ON k.id=w.ksiazka_id WHERE w.data_zwrotu IS NOT NULL GROUP BY k.gatunek ORDER BY srednia DESC',1,'2026-03-14 20:19:28'),
	 (1,'Zadanie 7. (0–2) Czytelnicy którzy wypożyczali każdy gatunek','hard','Podaj imię i nazwisko czytelników, którzy wypożyczyli co najmniej jedną książkę z KAŻDEGO gatunku obecnego w bazie. Posortuj po nazwisku.','GROUP BY c.id HAVING COUNT(DISTINCT k.gatunek) = (SELECT COUNT(DISTINCT gatunek) FROM ksiazki).','SELECT c.imie, c.nazwisko FROM czytelnicy c JOIN wypozyczenia w ON c.id=w.czytelnik_id JOIN ksiazki k ON w.ksiazka_id=k.id GROUP BY c.id HAVING COUNT(DISTINCT k.gatunek)=(SELECT COUNT(DISTINCT gatunek) FROM ksiazki) ORDER BY c.nazwisko',1,'2026-03-14 20:19:28'),
	 (2,'Zadanie 8. (0–2) Produkt o największych łącznych przychodach','hard','Podaj nazwę produktu, który wygenerował największy łączny przychód (suma ilosc * cena_jednostkowa ze wszystkich pozycji zamówień). Istnieje dokładnie jeden taki produkt.','JOIN pozycje_zamowien, GROUP BY produkt_id, SUM(ilosc*cena_jednostkowa), ORDER BY DESC LIMIT 1.','SELECT p.nazwa FROM produkty p JOIN pozycje_zamowien pz ON p.id=pz.produkt_id GROUP BY p.id ORDER BY SUM(pz.ilosc*pz.cena_jednostkowa) DESC LIMIT 1',1,'2026-03-14 20:19:28'),
	 (2,'Zadanie 9. (0–2) Klienci bez żadnego zrealizowanego zamówienia','hard','Podaj imię i nazwisko klientów, którzy nie mają ani jednego zamówienia o statusie ''zrealizowane''. Uwzględnij też klientów bez żadnych zamówień. Posortuj po nazwisku.','NOT IN: WHERE id NOT IN (SELECT klient_id FROM zamowienia WHERE status=''zrealizowane'').','SELECT imie, nazwisko FROM klienci WHERE id NOT IN (SELECT klient_id FROM zamowienia WHERE status=''zrealizowane'') ORDER BY nazwisko',1,'2026-03-14 20:19:28'),
	 (2,'Zadanie 10. (0–2) Kategoria z największą średnią ceną produktów aktywnych','hard','Podaj nazwę kategorii, której aktywne produkty (aktywny = 1) mają największą średnią cenę. Istnieje dokładnie jeden taki wynik.','JOIN kategorie, WHERE aktywny=1, GROUP BY kategoria_id, ORDER BY AVG(cena) DESC LIMIT 1.','SELECT k.nazwa FROM kategorie k JOIN produkty p ON k.id=p.kategoria_id WHERE p.aktywny=1 GROUP BY k.id ORDER BY AVG(p.cena) DESC LIMIT 1',1,'2026-03-14 20:19:28');
INSERT INTO matura_db.sql_tasks (scenario_id,title,difficulty,description,hint,solution,is_active,created_at) VALUES
	 (2,'Zadanie 11. (0–2) Wartość niezrealizowanych zamówień wg klienta','hard','Dla każdego klienta mającego przynajmniej jedno niezrealizowane zamówienie podaj imię, nazwisko i łączną wartość tych zamówień (suma ilosc*cena_jednostkowa). Posortuj malejąco po wartości.','WHERE z.data_realizacji IS NULL, JOIN pozycje_zamowien, GROUP BY klient_id, SUM(ilosc*cena_jednostkowa).','SELECT kl.imie, kl.nazwisko, SUM(pz.ilosc*pz.cena_jednostkowa) as wartosc FROM klienci kl JOIN zamowienia z ON kl.id=z.klient_id JOIN pozycje_zamowien pz ON z.id=pz.zamowienie_id WHERE z.data_realizacji IS NULL GROUP BY kl.id ORDER BY wartosc DESC',1,'2026-03-14 20:19:28'),
	 (2,'Zadanie 12. (0–2) Produkty nigdy nie zamówione','medium','Podaj nazwy produktów, które nie zostały ani razu zamówione (nie ma ich w żadnej pozycji zamówienia). Posortuj alfabetycznie.','WHERE id NOT IN (SELECT DISTINCT produkt_id FROM pozycje_zamowien).','SELECT nazwa FROM produkty WHERE id NOT IN (SELECT DISTINCT produkt_id FROM pozycje_zamowien) ORDER BY nazwa',1,'2026-03-14 20:19:28'),
	 (3,'Zadanie 13. (0–2) Zawodnik z największą liczbą wygranych meczów','hard','Zawodnik wygrywa mecz gdy gra białymi i wynik = ''W'', lub gdy gra czarnymi i wynik = ''B''. Podaj imię, nazwisko i łączną liczbę wygranych meczów zawodnika z największą ich liczbą. Istnieje dokładnie jeden taki zawodnik.','Zlicz wygrane jako biały: WHERE bialy_id=z.id AND wynik=''W'', i jako czarny: WHERE czarny_id=z.id AND wynik=''B''. Sumuj oba przypadki.','SELECT z.imie, z.nazwisko, COUNT(*) as wygrane FROM zawodnicy z JOIN mecze m ON (z.id=m.bialy_id AND m.wynik=''W'') OR (z.id=m.czarny_id AND m.wynik=''B'') GROUP BY z.id ORDER BY wygrane DESC LIMIT 1',1,'2026-03-14 20:19:28'),
	 (3,'Zadanie 14. (0–2) Zawodnicy z Polski w więcej niż 1 turnieju','hard','Podaj imię, nazwisko i liczbę turniejów zawodników z Polski, którzy brali udział (jako biały lub czarny) w więcej niż jednym turnieju. Posortuj po nazwisku.','INNER JOIN mecze (biały lub czarny), COUNT(DISTINCT turniej_id) > 1, WHERE kraj=''Polska''.','SELECT z.imie, z.nazwisko, COUNT(DISTINCT m.turniej_id) as turnieje FROM zawodnicy z JOIN mecze m ON z.id=m.bialy_id OR z.id=m.czarny_id WHERE z.kraj=''Polska'' GROUP BY z.id HAVING COUNT(DISTINCT m.turniej_id)>1 ORDER BY z.nazwisko',1,'2026-03-14 20:19:28'),
	 (3,'Zadanie 15. (0–2) Turniej z największym odsetkiem remisów','hard','Podaj nazwę turnieju, w którym odsetek remisów (mecze z wynikiem ''R'' do wszystkich meczów) był największy. Istnieje dokładnie jeden taki turniej. Wyraź wynik jako wartość dziesiętną zaokrągloną do 2 miejsc.','ROUND(SUM(CASE WHEN wynik=''R'' THEN 1 ELSE 0 END) * 1.0 / COUNT(*), 2), GROUP BY turniej_id.','SELECT t.nazwa FROM turnieje t JOIN mecze m ON t.id=m.turniej_id GROUP BY t.id ORDER BY ROUND(SUM(CASE WHEN m.wynik=''R'' THEN 1.0 ELSE 0 END)/COUNT(*),2) DESC LIMIT 1',1,'2026-03-14 20:19:28'),
	 (3,'Zadanie 16. (0–2) Zawodnicy którzy nigdy nie remisowali','hard','Podaj imię, nazwisko i kraj zawodników, którzy rozegrali co najmniej jeden mecz, ale nie zremisowali ani razu (żaden mecz z ich udziałem nie ma wyniku ''R''). Posortuj po nazwisku.','Zawodnik grał: (bialy_id=id OR czarny_id=id). Brak remisu: nie istnieje mecz z wynikiem R i udziałem tego zawodnika.','SELECT DISTINCT z.imie, z.nazwisko, z.kraj FROM zawodnicy z WHERE z.id IN (SELECT bialy_id FROM mecze UNION SELECT czarny_id FROM mecze) AND z.id NOT IN (SELECT bialy_id FROM mecze WHERE wynik=''R'' UNION SELECT czarny_id FROM mecze WHERE wynik=''R'') ORDER BY z.nazwisko',1,'2026-03-14 20:19:28'),
	 (3,'Zadanie 17. (0–2) Ranking zawodników w turnieju Grand Chess Tour Warszawa','hard','Dla turnieju „Grand Chess Tour Warszawa" oblicz punktację każdego zawodnika: wygrana = 1 pkt, remis = 0.5 pkt, przegrana = 0 pkt. Podaj imię, nazwisko i punkty, posortuj malejąco po punktach, a przy równej liczbie punktów — alfabetycznie po nazwisku.','SUM(CASE WHEN bialy_id=z.id AND wynik=''W'' THEN 1 WHEN bialy_id=z.id AND wynik=''R'' THEN 0.5 ... END).','SELECT z.imie, z.nazwisko, SUM(CASE WHEN m.bialy_id=z.id AND m.wynik=''W'' THEN 1.0 WHEN m.bialy_id=z.id AND m.wynik=''R'' THEN 0.5 WHEN m.czarny_id=z.id AND m.wynik=''B'' THEN 1.0 WHEN m.czarny_id=z.id AND m.wynik=''R'' THEN 0.5 ELSE 0 END) as pkt FROM zawodnicy z JOIN mecze m ON z.id=m.bialy_id OR z.id=m.czarny_id WHERE m.turniej_id=1 GROUP BY z.id ORDER BY pkt DESC, z.nazwisko',1,'2026-03-14 20:19:28');
